#ifndef STYLE_PROPERTIES_H
#define STYLE_PROPERTIES_H

enum class StyleProperty {
    UNKNOWN, DISPLAY, WIDTH, HEIGHT, 
    MARGIN_TOP, MARGIN_RIGHT, MARGIN_BOTTOM, MARGIN_LEFT,
    PADDING_TOP, PADDING_RIGHT, PADDING_BOTTOM, PADDING_LEFT,
    BORDER_STYLE, BORDER_WIDTH, BORDER_COLOR,
    COLOR, BACKGROUND_COLOR,
};

#endif